### ISSUE TITLE
Cannot run example on Armv7 panicked at 'overflow when adding duration to instant'

### ISSUE THREAD

**Issue by frjol** [webrtc-rs/webrtc#175]
Based on the discussion from the issue in the example here https://github.com/webrtc-rs/examples/issues/5 

I have an issue running the example on a Raspberry Pi Zero 2 W armv7l.

It seems related this issue https://github.com/chronotope/chrono/issues/343

```
$ cat test.sdp | RUST_BACKTRACE=full ./play-from-disk-h264 --video output.h264
thread 'main' panicked at 'overflow when adding duration to instant', library/std/src/time.rs:550:31
stack backtrace:
   0:   0xab3708 - std::backtrace_rs::backtrace::libunwind::trace::h4bf3e5497ce7d0d1
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:   0xab3708 - std::backtrace_rs::backtrace::trace_unsynchronized::h6b664ef1002045f8
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0xab3708 - std::sys_common::backtrace::_print_fmt::h077a74dd0fd95079
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:   0xab3708 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha65a6b17248d4482
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:   0xad925c - core::fmt::write::h682b611af217d220
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:   0xaaccec - std::io::Write::write_fmt::h8cc061d257db1323
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:   0xab55d4 - std::sys_common::backtrace::_print::h8ea36d0a4c8c8101
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:   0xab55d4 - std::sys_common::backtrace::print::h27c30ada45da6e69
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:   0xab55d4 - std::panicking::default_hook::{{closure}}::h2ac34510ecc99ccd
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:   0xab5030 - std::panicking::default_hook::ha1d2ed057431f9b0
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:   0xab5cac - std::panicking::rust_panic_with_hook::h17c1e02f294ac808
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:   0xab5788 - std::panicking::begin_panic_handler::{{closure}}::h9573bd22277952be
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  12:   0xab3c90 - std::sys_common::backtrace::__rust_end_short_backtrace::h99bf7f87f84ce00f
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:   0xab56e0 - rust_begin_unwind
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:   0x4aa220 - core::panicking::panic_fmt::h9bf8e44e3548ebaf
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  15:   0x4aa128 - core::option::expect_failed::h7b469729e8e287e8
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:1615:5
  16:   0xab34d0 - core::option::Option<T>::expect::hbd7ce046258044e2
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:698:21
  17:   0xab34d0 - <std::time::SystemTime as core::ops::arith::Add<core::time::Duration>>::add::h8c303cffbd39972b
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/time.rs:550:9
  18:   0x70331c - chrono::datetime::<impl core::convert::From<chrono::datetime::DateTime<Tz>> for std::time::SystemTime>::from::habe72c9a7cc9cb26
  19:   0x6fda70 - webrtc::peer_connection::certificate::RTCCertificate::from_params::hee995bbe460172fb
  20:   0x6fe394 - webrtc::peer_connection::certificate::RTCCertificate::from_key_pair::h1a7e64a6836c2821
  21:   0x76a264 - webrtc::peer_connection::RTCPeerConnection::init_configuration::he526c67849077f08
  22:   0x668dd4 - play_from_disk_h264::main::{{closure}}::heac723bac7819863
  23:   0x5540f8 - tokio::park::thread::CachedParkThread::block_on::hf1ad0ac1d6238337
  24:   0x55421c - tokio::runtime::thread_pool::ThreadPool::block_on::h2e6b8d84876a02e8
  25:   0x692a78 - play_from_disk_h264::main::h6f9f4e760d1648f7
  26:   0x53d0c0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb6001fa900b53d38
  27:   0x559cdc - std::rt::lang_start::{{closure}}::h57b02cdf22d786ad
  28:   0xab62d8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7ba1bdda2f342471
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  29:   0xab62d8 - std::panicking::try::do_call::h4c3c648f73078093
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  30:   0xab62d8 - std::panicking::try::h06ab9d03dd62fbbd
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  31:   0xab62d8 - std::panic::catch_unwind::h82421e9e18ace5da
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  32:   0xab62d8 - std::rt::lang_start_internal::{{closure}}::h1cbfee7e0ebe057d
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  33:   0xab62d8 - std::panicking::try::do_call::he9d4b690fd004a7c
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  34:   0xab62d8 - std::panicking::try::hbd6ed135d4dc763a
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  35:   0xab62d8 - std::panic::catch_unwind::h45dacf89f176e04b
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  36:   0xab62d8 - std::rt::lang_start_internal::hd4ee3abcdb019f91
                       at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  37:   0x692f30 - main
  38: 0x76d29be0 - __libc_start_main
                       at ./csu/./csu/libc-start.c:308:16
```
I made a workaround here https://github.com/frjol/webrtc/tree/time-overflow-armv7-workaround which works for me but might not be the optimal solution.

I replace the code here 
https://github.com/webrtc-rs/webrtc/blob/master/src/peer_connection/certificate.rs#L74

from 

```
let expires = params.not_after.into();
```
to
 
```
let expires = SystemTime::now().add(Duration::from_secs(172800)); //60*60*48 or 2 days
```

@rainliu suggested I make a PR for this.

Thanks for your feedback

**Comment by k0nserv** [comment]
@frjol Can this be closed?

**Comment by frjol** [comment]
@k0nserv Yes! Thank you for tracking this.
